apiVersion: apps/v1
kind: Deployment
metadata:
    name: damage
    namespace: pedelec
spec:
    replicas: 1
    selector:
        matchLabels:
            app: damage
    template:
        metadata:
            labels:
                app: damage
        spec:
            containers:
            - name: damage
              image: gitlab.lrz.de:5005/ase/ipraktikum/pedelec-app/damage:feat-add-microservices
              ports:
              - containerPort: 8082
                name: damage-api
        
              resources: # It is always a good idea to limit the resources of your containers - We did not cover this in the lecture, but it is a good practice to do so.
                limits:
                    cpu: "1"
                    memory: "512Mi"