version: "3.8"
services:
  reservation:
    build:
      context: ./reservation
      dockerfile: Dockerfile
    image: ghcr.io/ls1intum/pedelec-app/reservation:${RESERVATION_IMAGE_TAG:-latest}
    ports:
      - 8080:8080
  location:
    build:
      context: ./location
      dockerfile: Dockerfile
    image: ghcr.io/ls1intum/pedelec-app/location:${LOCATION_IMAGE_TAG:-latest}
    ports:
      - 8081:8081
  damage:
    build:
      context: ./damage
      dockerfile: Dockerfile
    image: ghcr.io/ls1intum/pedelec-app/damage:${DAMAGE_IMAGE_TAG:-latest}
    ports:
      - 8082:8082
