apiVersion: v1
kind: Service
metadata:
  name: pedelec-reservation-service
  namespace: pedelec
spec:
  selector:
    app: reservation
  ports:
    - protocol: TCP
      port: 80
      targetPort: reservation-api