# Since we're pulling our images from our private registry, we need to provide the credentials to the cluster.
# You can find the details how to create this secrete here: https://chris-vermeulen.com/using-gitlab-registry-with-kubernetes/

# This secret is allowed to pull the Pedelec images from the gitlab.lrz.de registry. 
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-lrz
  namespace: pedelec # Hardcoded namespace - change this to your own namespace!
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIubHJ6LmRlOjUwMDUiOnsidXNlcm5hbWUiOiJnaXRsYWIrZGVwbG95LXRva2VuLTE3NjAiLCJwYXNzd29yZCI6ImdsZHQtWExYNWdVRkR6eXMteTZHUC0zVHQiLCJlbWFpbCI6ImVtYWlsIiwiYXV0aCI6IloybDBiR0ZpSzJSbGNHeHZlUzEwYjJ0bGJpMHhOell3T21kc1pIUXRXRXhZTldkVlJrUjZlWE10ZVRaSFVDMHpWSFE9In19fQ==

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pedelec
  namespace: ga58roj # Hardcoded namespace - change this to your own namespace!
imagePullSecrets:
- name: gitlab-lrz  