apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pedelec-ingress
  namespace: pedelec # Hardcoded namespace - change this to your own namespace!
spec:
  rules:
  - host: pedelec-workshop.k8s.ase.cit.tum.de
    http:
      paths:
      - pathType: Prefix
        path: "/pedelec"
        backend:
          service:
            name: pedelec-reservation-service
            port:
              number: 80
      - pathType: Prefix
        path: "/reservation"
        backend:
          service:
            name: pedelec-reservation-service
            port:
              number: 80
      - pathType: Prefix
        path: "/location"
        backend:
          service:
            name: pedelec-location-service
            port:
              number: 80
      - pathType: Prefix
        path: "/damage"
        backend:
          service:
            name: pedelec-damage-service
            port:
              number: 80